name: rim_chess
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.7
  dotted_border: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.8
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  http: ^1.2.0
  cached_network_image: ^3.3.1
  skeletonizer: ^1.1.0

  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  just_audio: ^0.9.36
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: DINNext
      fonts:
        - asset: assets/fonts/DINNext-Regular.ttf
